# Generated by Django 3.0.5 on 2020-05-31 00:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200531_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeranswer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('298a855b-0b15-49b3-89cd-e0aa8adc3a3c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ce361a1-fd2c-468a-81bf-16356a99193f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ae651082-6b44-4243-a4c3-c5771b42fce3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
