# Generated by Django 3.0.5 on 2020-04-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_playeranswer_submitted_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playeranswer',
            old_name='submitted_data',
            new_name='submitted_date',
        ),
    ]
