# Generated by Django 3.0.5 on 2020-04-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200416_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='instances_played',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
