# Generated by Django 3.0.5 on 2020-04-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200417_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeranswer',
            name='quiz',
        ),
    ]
