# Generated by Django 3.0.5 on 2020-04-21 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20200420_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playeranswer',
            options={'ordering': ['-submitted_date']},
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1da74568-8658-4ec9-b16e-d0d59ead2373'), primary_key=True, serialize=False),
        ),
    ]
