# Generated by Django 3.0.5 on 2020-04-21 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20200421_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playeranswer',
            options={'get_latest_by': ['submitted_date'], 'ordering': ['-submitted_date']},
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1dab44fb-0336-41a6-8815-5b108c683e43'), primary_key=True, serialize=False),
        ),
    ]
