# Generated by Django 3.0.5 on 2020-04-23 10:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20200421_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playeranswers', to='quiz.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d00931e2-c66a-4af3-8933-6e0b4cbe2c09'), primary_key=True, serialize=False),
        ),
    ]
