# Generated by Django 3.0.5 on 2020-04-23 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20200423_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playeranswer',
            options={},
        ),
        migrations.RemoveField(
            model_name='playeranswer',
            name='submitted_date',
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4c781e9f-ec3e-4ed6-81b6-0f4488da840e'), primary_key=True, serialize=False),
        ),
    ]
