# Generated by Django 3.0.5 on 2020-05-06 12:02

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20200424_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidquiz',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('408f5008-4dbd-4a08-92ec-338622ab7cb1'), primary_key=True, serialize=False),
        ),
    ]
