# Generated by Django 3.0.5 on 2020-04-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp_field',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
