# Generated by Django 3.0.5 on 2020-04-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='temp_field',
        ),
    ]
