# Generated by Django 3.0.5 on 2020-04-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_temp_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='receive_email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
