# Generated by Django 3.0.5 on 2020-04-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200410_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='receive_email',
            field=models.BooleanField(default=False),
        ),
    ]
